name: Run GNS3 project and tests

on:
  pull_request:
    branches:
      - main

jobs:
   run-gns3-and-tests:
    name: Run GNS3 project and tests
    runs-on: [gns3]
    env:
      GNS3_SERVER_HOST: 127.0.0.1
      GNS3_SERVER_PORT: 3080
      GNS3_PROJECT_PATH: ${{ github.workspace }}/PoC.gns3
      GNS3_PROJECT_NAME: netman-poc
      GNS3_API_USERNAME: ${{ secrets.GNS3_API_USERNAME }}
      GNS3_API_PASSWORD: ${{ secrets.GNS3_API_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt


      # Start GNS3 server in background and wait for it to be ready
      - name: Start GNS3 server
        run: pipeline/startGNS3.sh


      # Set up GNS3 project and start nodes
      - name: Import GNS3 project
        run: python3 pipeline/load_project.py

      - name: Start all nodes
        run: python3 pipeline/start_all_nodes.py


      # Wait for nodes to boot up
      - name: Wait for routers to boot
        run: pipeline/waitForRouter.sh


      # Configure routers
      # - name: Configure routers
      #   run: python3 src/main.py


      # Reload Prometheus and wait for scrape interval
      - name: Reload Prometheus and wait for OSPF convergence
        run: |
          curl --silent --fail -X POST http://localhost:9090/-/reload
          sleep 60

      # Tests
      - name: Run tests
        run: python3 -m pytest tests -v


      # Kill GNS3 server and re-symlink project directory to repo
      - name: Cleanup
        if: always()
        run: |
          pkill -f dynamips || true
          pkill -f gns3server || true
          ln -sfn /home/netman/netman-poc /home/netman/GNS3/projects/fa306d8b-9395-4962-98c9-fc21fe61755f
